services:
    oro_ui.layout_expression.asset:
        class: Oro\Bundle\UIBundle\Layout\ConfigExpression\Asset
        arguments:
            - @assets.packages
        tags:
            - { name: oro_layout.expression, alias: asset }
