parameters:
    #processors
    oro_ldap.importexport.processor.import.user.class:      Oro\Bundle\LDAPBundle\ImportExport\LdapUserImportProcessor

    #writers
    oro_ldap.importexport.writer.ldap.user.class:           Oro\Bundle\LDAPBundle\ImportExport\LdapUserWriter
    oro_ldap.importexport.writer.entity.user.class:         Oro\Bundle\LDAPBundle\ImportExport\UserWriter

    #readers
    oro_ldap.importexport.reader.ldap.user.class:           Oro\Bundle\LDAPBundle\ImportExport\LdapUserReader

services:
    oro_ldap.importexport.reader.ldap.user:
        class: %oro_ldap.importexport.reader.ldap.user.class%
        arguments:
            - @oro_importexport.context_registry
            - @oro_integration.provider.connector_context_mediator
            - @oro_ldap.provider.channel_manager

    oro_ldap.importexport.writer.ldap.user:
        class: %oro_ldap.importexport.writer.ldap.user.class%
        arguments:
            - @oro_user.manager
            - @oro_importexport.context_registry
            - @oro_integration.provider.connector_context_mediator
            - @oro_ldap.provider.channel_manager

    oro_ldap.importexport.writer.entity.user:
        parent: oro_importexport.writer.entity
        class: %oro_ldap.importexport.writer.entity.user.class%

    oro_ldap.importexport.processor.import.user:
        class: %oro_ldap.importexport.processor.import.user.class%
        arguments:
            - @oro_user.manager
            - @oro_importexport.context_registry
            - @oro_integration.provider.connector_context_mediator
            - @oro_ldap.provider.channel_manager
