placeholders:
    index_navButtons_before:
        items:
            ldap_import_users_button: ~
            ldap_export_users_button: ~

items:
    ldap_import_users_button:
        template: OroLDAPBundle:Synchronization:importUsersLink.html.twig
        applicable: @oro_ui.placeholder.filter->isEqual($entity_class$, %oro_user.entity.class%)
        acl: oro_ldap_import_users
    ldap_export_users_button:
        template: OroLDAPBundle:Synchronization:exportUsersLink.html.twig
        applicable: @oro_ui.placeholder.filter->isEqual($entity_class$, %oro_user.entity.class%)
        acl: oro_ldap_export_users
