parameters:
    #fr3ed
    fr3d_ldap.security.authentication.provider.class:   Oro\Bundle\LDAPBundle\Security\LdapProvider
    fr3d_ldap.ldap_driver.zend.class:                   Oro\Bundle\LDAPBundle\LDAP\ZendLdapDriver
    #providers
    oro_ldap.provider.user.class:                       Oro\Bundle\LDAPBundle\Provider\UserProvider
    #integration
    oro_ldap.provider.channel_type.class:               Oro\Bundle\LDAPBundle\Provider\ChannelType
    oro_ldap.provider.connector.user.class:             Oro\Bundle\LDAPBundle\Provider\Connector\UserLdapConnector
    oro_ldap.provider.transport.ldap.class:             Oro\Bundle\LDAPBundle\Provider\Transport\LdapTransport
    #event listeners
    oro_ldap.event_listener.user_change_listener.class: Oro\Bundle\LDAPBundle\EventListener\UserChangeListener

services:
    fr3d_ldap.security.authentication.provider:
        class: %fr3d_ldap.security.authentication.provider.class%
        arguments:
            - @security.user_checker
            - ""
            - ""
            - @oro_ldap.ldap.factory.ldap_manager
            - %security.authentication.hide_user_not_found%

    oro_ldap.ldap.factory.ldap_manager:
        class: Oro\Bundle\LDAPBundle\LDAP\Factory\LdapManagerFactory
        arguments:
            - @doctrine
            - @fr3d_ldap.user_manager
            - @logger

    oro_ldap.provider.user:
        class: %oro_ldap.provider.user.class%
        arguments:
            - @doctrine

    oro_ldap.provider.channel_type:
        class: %oro_ldap.provider.channel_type.class%
        tags:
            - { name: oro_integration.channel, type: ldap }

    oro_ldap.provider.ldap.transport:
        class: %oro_ldap.provider.transport.ldap.class%
        tags:
            - { name: oro_integration.transport, type: ldap, channel_type: ldap }

    oro_ldap.provider.connector.user:
        class: %oro_ldap.provider.connector.user.class%
        tags:
            - { name: oro_integration.connector, type: user, channel_type: ldap }

    oro_ldap.ldap_channel_manager.link:
        tags:
            - { name: oro_service_link,  service: oro_ldap.ldap.ldap_channel_manager }

    oro_ldap.ldap.ldap_channel_manager:
        class: Oro\Bundle\LdapBundle\LDAP\LdapChannelManager
        arguments: [@doctrine, @oro_ldap.ldap.factory.ldap_manager]

    oro_ldap.event_listener.user_change_listener.class:
        class:  %oro_ldap.event_listener.user_change_listener.class%
        arguments:
            - @oro_ldap.ldap_channel_manager.link
        tags:
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postFlush }
