parameters:
    fr3d_ldap.security.authentication.provider.class:   Oro\Bundle\LDAPBundle\Security\LdapProvider
    fr3d_ldap.ldap_driver.zend.class:                   Oro\Bundle\LDAPBundle\LDAP\ZendLdapDriver
    oro_ldap.provider.user.class:                       Oro\Bundle\LDAPBundle\Provider\UserProvider
    oro_ldap.provider.channel_type.class:               Oro\Bundle\LDAPBundle\Provider\ChannelType
    oro_ldap.provider.ldap_transport.class:             Oro\Bundle\LDAPBundle\Provider\Transport\LdapTransport
    oro_ldap.form.type.ldap_transport_setting.class:    Oro\Bundle\LDAPBundle\Form\Type\LdapTransportSettingsFormType
    oro_ldap.manager.import.class:                      Oro\Bundle\LDAPBundle\Manager\ImportManager
    oro_ldap.manager.export.class:                      Oro\Bundle\LDAPBundle\Manager\ExportManager
    oro_ldap.event_listener.user_change_listener.class: Oro\Bundle\LDAPBundle\EventListener\UserChangeListener

services:
    fr3d_ldap.security.authentication.provider:
        class: %fr3d_ldap.security.authentication.provider.class%
        arguments:
            - @security.user_checker
            - ""
            - ""
            - @fr3d_ldap.ldap_manager
            - @oro_config.global
            - %security.authentication.hide_user_not_found%

    oro_ldap.ldap.ldap_manager:
        class: Oro\Bundle\LDAPBundle\LDAP\LdapManager
        arguments:
            - @doctrine
            - @fr3d_ldap.ldap_driver
            - @fr3d_ldap.user_manager
            - %fr3d_ldap.ldap_manager.parameters%
        calls:
            - [updateOroConfiguration, [@oro_config.global]]

    oro_ldap.provider.user:
        class: %oro_ldap.provider.user.class%
        arguments:
            - @doctrine

    oro_ldap.provider.channel_type:
        class: %oro_ldap.provider.channel_type.class%
        tags:
            - { name: oro_integration.channel, type: ldap }

    oro_ldap.provider.ldap.transport:
        class: %oro_ldap.provider.ldap_transport.class%
        tags:
            - { name: oro_integration.transport, type: ldap, channel_type: ldap }

    oro_ldap.manager.import:
        class: %oro_ldap.manager.import.class%
        arguments:
            - @fr3d_ldap.ldap_manager
            - @oro_user.manager
            - @doctrine
            - @oro_ldap.provider.user
            - @logger
        tags:
            - { name: monolog.logger, channel: oro_distribution }

    oro_ldap.manager.export:
        class: %oro_ldap.manager.export.class%
        arguments:
            - @fr3d_ldap.ldap_manager
            - @oro_user.manager
            - @oro_ldap.provider.user
            - @logger
        tags:
            - { name: monolog.logger, channel: oro_distribution }

    oro_ldap.ldap_manager.link:
        tags:
            - { name: oro_service_link,  service: oro_ldap.ldap.ldap_manager }

    oro_ldap.event_listener.user_change_listener.class:
        class:  %oro_ldap.event_listener.user_change_listener.class%
        arguments:
            - @oro_ldap.ldap_manager.link
        tags:
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postFlush }
