parameters:
    fr3d_ldap.security.authentication.provider.class: Oro\Bundle\LDAPBundle\Security\LdapProvider
    fr3d_ldap.ldap_driver.zend.class:                 Oro\Bundle\LDAPBundle\LDAP\ZendLdapDriver
    oro_ldap.extension.user_type.class:               Oro\Bundle\LDAPBundle\Form\Extension\UserTypeExtension
    oro_ldap.provider.user.class:                     Oro\Bundle\LDAPBundle\Provider\UserProvider
    oro_ldap.provider.channel_type.class:             Oro\Bundle\LDAPBundle\Provider\ChannelType
    oro_ldap.provider.ldap_transport.class:           Oro\Bundle\LDAPBundle\Provider\Transport\LdapTransport
    oro_ldap.provider.connector.user.class:           Oro\Bundle\LDAPBundle\Provider\Connector\UserLdapConnector
    oro_ldap.manager.import.class:                    Oro\Bundle\LDAPBundle\Manager\ImportManager
    oro_ldap.manager.export.class:                    Oro\Bundle\LDAPBundle\Manager\ExportManager
    oro_ldap.importexport.reader.ldap.user.class:     Oro\Bundle\LDAPBundle\ImportExport\LdapUserReader
    oro_ldap.importexport.writer.ldap.user.class:     Oro\Bundle\LDAPBundle\ImportExport\LdapUserWriter

services:
    fr3d_ldap.security.authentication.provider:
        class: %fr3d_ldap.security.authentication.provider.class%
        arguments:
            - @security.user_checker
            - ""
            - ""
            - @fr3d_ldap.ldap_manager
            - @oro_config.global
            - %security.authentication.hide_user_not_found%

    oro_ldap.ldap.ldap_manager:
        class: Oro\Bundle\LDAPBundle\LDAP\LdapManager
        arguments:
            - @doctrine
            - @fr3d_ldap.ldap_driver
            - @fr3d_ldap.user_manager
            - %fr3d_ldap.ldap_manager.parameters%
        calls:
            - [updateOroConfiguration, [@oro_config.global]]

    oro_ldap.extension.user_type:
        class: %oro_ldap.extension.user_type.class%
        tags:
            - { name: form.type_extension, alias: oro_user_user }

    oro_ldap.provider.user:
        class: %oro_ldap.provider.user.class%
        arguments:
            - @doctrine

    oro_ldap.provider.channel_type:
        class: %oro_ldap.provider.channel_type.class%
        tags:
            - { name: oro_integration.channel, type: ldap }

    oro_ldap.provider.ldap.transport:
        class: %oro_ldap.provider.ldap_transport.class%
        tags:
            - { name: oro_integration.transport, type: ldap, channel_type: ldap }

    oro_ldap.provider.connector.user:
        class: %oro_ldap.provider.connector.user.class%
        tags:
            - { name: oro_integration.connector, type: user, channel_type: ldap }
        arguments: [@oro_importexport.context_registry, @oro_integration.logger.strategy, @oro_integration.provider.connector_context_mediator]

    oro_ldap.manager.import:
        class: %oro_ldap.manager.import.class%
        arguments:
            - @fr3d_ldap.ldap_manager
            - @oro_user.manager
            - @doctrine
            - @oro_ldap.provider.user
            - @logger
        tags:
            - { name: monolog.logger, channel: oro_distribution }

    oro_ldap.manager.export:
        class: %oro_ldap.manager.export.class%
        arguments:
            - @fr3d_ldap.ldap_manager
            - @oro_user.manager
            - @oro_ldap.provider.user
            - @logger
        tags:
            - { name: monolog.logger, channel: oro_distribution }

    oro_ldap.importexport.reader.ldap.user:
        class: %oro_ldap.importexport.reader.ldap.user.class%

    oro_ldap.importexport.writer.ldap.user:
        class: %oro_ldap.importexport.writer.ldap.user.class%
